# Generated by Django 4.2 on 2025-01-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='kategoriya nomi')),
            ],
            options={
                'verbose_name': 'kotegoriya',
                'verbose_name_plural': 'kotegoriyalar',
            },
        ),
        migrations.CreateModel(
            name='TovarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('about', models.TextField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.categorymodel', verbose_name='kategoriya')),
            ],
        ),
    ]
