# Generated by Django 4.2 on 2025-01-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_basketmodl'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Yetkazilmoqda', 'Yetkazilmoqda'), ('Yetkazildi', 'Yetkazildi'), ("To'landi", "To'landi")], max_length=200, null=True)),
                ('summa', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('basket', models.ManyToManyField(to='storeapp.basketmodl')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storeapp.userprofile')),
            ],
        ),
    ]
